config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/prices'
  get 'home/trends'
  post "/home/prices" => "home/prices"
  post "/home/trends" => "home/trends"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    require 'net/http'
    require 'json'
    
    # Grab News Data
    @url = 'https://min-api.cryptocompare.com/data/v2/news/?lang=EN'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @news = JSON.parse(@response)
    
    # Grab Price Data
    @prices_url = 'https://min-api.cryptocompare.com/data/pricemultifull?fsyms=BTC,ETH,XRP,ECH,EOS,LTC,ADA,XLM,MIOTA,USDT&tsyms=USD'
    @prices_uri = URI(@prices_url)
    @prices_response = Net::HTTP.get(@prices_uri)
    @prices = JSON.parse(@prices_response)
    
  end
  
  def prices
    require 'net/http'
    require 'json'
    @symbol = params[:sym]
    
    if @symbol
     @symbol = @symbol.upcase
      
       # Grab Price Data
      @quote_url = 'https://min-api.cryptocompare.com/data/pricemultifull?fsyms=' + @symbol + '&tsyms=USD'
      @quote_uri = URI(@quote_url)
      @quote_response = Net::HTTP.get(@quote_uri)
      @quote = JSON.parse(@quote_response)
      
    end
  end
  
  def
    trends
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to "Crypto_Grapes Analytics", root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      
      <li class="nav-item">
        <%= link_to "Get Prices", home_prices_path, class: "nav_link" %> 
        <%= link_to "Crypto_Grapes Trends", home_trends_path, class: "nav_link" %>
      </li>
    
    </ul>
    
    <%= form_tag home_prices_path, :method => 'POST', class: "form-inline my-2 my-lg-0" do %>
    <%= text_field_tag 'sym', nil, placeholder:'Crypto Symbol', class: "form-inline my-2 my-lg-0"%>
    <%= submit_tag 'Lookup', class: 'btn btn-outline-success my-2 my-sm-0'%>
    
    <% end %>
    
  </div>
</nav>

 

app/views/home/index.html.erb
<h1>Hello Glynis</h1><br/>

<table class="table table-sm table-striped table-bordered table-hover">
    <thead class="thead-light">
     <tr>
      <th scope="col">Name</th>
      <th scope="col">Price</th>
      <th scope="col">24h High</th>
      <th scope="col">24h Low</th>
      <th scope="col">Market Cap</th>
    </tr>
    </thead>
  <tbody>
        <% @prices["DISPLAY"].each do |key, value| %>
        
    <tr>
      <td><%= key  %></td>
      <td><%= value["USD"]["PRICE"] %></td>
      <td><%= value["USD"]["HIGHDAY"] %></td>
      <td><%= value["USD"]["LOWDAY"] %></td>
      <td><%= value["USD"]["MKTCAP"] %></td>
    </tr>
    
    <% end %>
    
  </tbody>
</table>

<% @prices["DISPLAY"].each do |key, value| %>
    <!--<%= key  %> - <%= value["USD"]["PRICE"] %><br/>-->
    <!--24h High: <%= value["USD"]["HIGHDAY"] %><br/>-->
    <!--24h Low: <%= value["USD"]["LOWDAY"] %><br/>-->
    <!--MarketCap: <%= value["USD"]["MKTCAP"] %><br/>-->

<% end %>

<br/>

<div class="container">
  <div class="row">

    <% for x in @news["Data"] %>
        <div class="col-sm">
            <div class="card" style="width: 18rem;">
                <img class="card-img-top" src="<%= x["imageurl"] %>" alt="x["source"] ">
                <div class="card-body">
                 <h5 class="card-title"><%= x["title"] %></h5>
                 <p class="card-text"><%= x["body"] %><br/><br/></p>
                 <a href="<%= x["url"] %>" class="btn btn-secondary">Read More...</a>
                </div>
             </div>
          <br/>
        </div>
    <% end %>
  </div>    
</div>

app/views/home/prices.html.erb
<% @symbol %>

 <% if @symbol %>
   <% if @quote["Respone"] %>
      <h4>That Crypto Symbol Doesn't Exist. Please Try Again.</h4>
   <% else %>
        
        <% @quote["DISPLAY"].each do |key, value| %>
           <div class="jumbotron">
           <h1 class="display-4"><% key %></h1>
           Price: <%= value["USD"]["PRICE"] %><br/>
           24hr High: <%= value["USD"]["HIGHDAY"] %><br/>
           24hr Low: <%= value["USD"]["LOWDAY"] %><br/>
           Market Cap: <%= value["USD"]["MKTCAP"] %><br/>
           </div>
        <% end %>
  
    <% end %>

<% else %>
   <h4>Oops!Please enter a crypto symbol in the form above dummy...</h4>
<% end %>
     

app/views/home/trends.html.erb
<h1>Cryto_Grapes Trends</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crypto_Grapes Analytics</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<%= render 'home/navbar' %>
  
<br/>
<div class="container"

<%= yield %>
</div></div>

</body>
</html>